In [3]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.linear_model import LogisticRegression

In [4]:
source = "train_energy_data.csv"
df = pd.read_csv(source)

df.dropna()
# Protect in case of empty records - however, dataset does not have any empty rows

BuildingType = df.loc[:, ["Building Type"]].values

buildingTypeFiltered = []
for i in range(BuildingType.shape[0]):
  if (BuildingType[i] == "Residential"):
    buildingTypeFiltered.append(0)
  elif (BuildingType[i] == "Commercial"):
    buildingTypeFiltered.append(1)
  else:
    buildingTypeFiltered.append(2)

buildingTypeFiltered = np.array(buildingTypeFiltered)



squareFootageI = df.loc[:, ["Square Footage"]].values
squareFootage = []
for i in range(squareFootageI.shape[0]):
  squareFootage.append(int(squareFootageI[i].item()))
squareFootage = np.array(squareFootage)


numberOfOccupantsI = df.loc[:, ["Number of Occupants"]].values
numberOfOccupants = []
for i in range(numberOfOccupantsI.shape[0]):
  numberOfOccupants.append(int(numberOfOccupantsI[i].item()))
numberOfOccupants = np.array(numberOfOccupants)


appliancesUsedI = df.loc[:, ["Appliances Used"]].values
appliancesUsed = []
for i in range(appliancesUsedI.shape[0]):
  appliancesUsed.append(float(appliancesUsedI[i].item()))
appliancesUsed = np.array(appliancesUsed)


averageTemperatureI = df.loc[:, ["Average Temperature"]].values
averageTemperature = []
for i in range(averageTemperatureI.shape[0]):
  averageTemperature.append(float(averageTemperatureI[i].item()))
averageTemperature = np.array(averageTemperature)


dayOfWeekI = df.loc[:, ["Day of Week"]].values
dayOfWeek = []
for i in range(dayOfWeekI.shape[0]):
  if (dayOfWeekI[i] == "Weekend"):
    dayOfWeek.append(4)
  else:
    dayOfWeek.append(5)
dayOfWeek = np.array(dayOfWeek)


energyConsumptionI = df.loc[:, ["Energy Consumption"]].values
energyConsumption = []
for i in range(energyConsumptionI.shape[0]):
  energyConsumption.append(float(energyConsumptionI[i].item()))
energyConsumption = np.array(energyConsumption)


Xtrain = np.column_stack((energyConsumption, squareFootage))
ytrain = buildingTypeFiltered
print(Xtrain.shape)
print(ytrain.shape)


print(Xtrain[:15])


(1000, 4)
(1000,)
[[7.06300e+03 1.00000e+01 7.60000e+01 2.71395e+03]
 [4.43720e+04 4.50000e+01 6.60000e+01 5.74499e+03]
 [1.92550e+04 1.70000e+01 3.70000e+01 4.10124e+03]
 [1.32650e+04 4.10000e+01 1.40000e+01 3.00914e+03]
 [1.33750e+04 1.80000e+01 2.60000e+01 3.27917e+03]
 [3.73770e+04 3.20000e+01 2.60000e+01 4.68767e+03]
 [3.86380e+04 1.40000e+01 9.20000e+01 5.52683e+03]
 [3.49500e+04 1.80000e+01 6.00000e+01 4.11632e+03]
 [2.97410e+04 4.40000e+01 9.90000e+01 5.84165e+03]
 [1.74670e+04 3.60000e+01 4.20000e+01 3.41913e+03]
 [2.77020e+04 1.40000e+01 7.10000e+01 4.31861e+03]
 [4.72650e+04 4.40000e+01 4.00000e+00 5.20634e+03]
 [1.91390e+04 3.40000e+01 9.70000e+01 4.07021e+03]
 [1.78200e+04 8.00000e+00 1.10000e+01 2.57198e+03]
 [4.58680e+04 1.90000e+01 9.70000e+01 5.03114e+03]]


In [5]:
source = "test_energy_data.csv"
df = pd.read_csv(source)

df.dropna()
# Protect in case of empty records - however, dataset does not have any empty rows

BuildingType = df.loc[:, ["Building Type"]].values

buildingTypeFiltered = []
for i in range(BuildingType.shape[0]):
  if (BuildingType[i] == "Residential"):
    buildingTypeFiltered.append(0)
  elif (BuildingType[i] == "Commercial"):
    buildingTypeFiltered.append(1)
  else:
    buildingTypeFiltered.append(2)

buildingTypeFiltered = np.array(buildingTypeFiltered)



squareFootageI = df.loc[:, ["Square Footage"]].values
squareFootage = []
for i in range(squareFootageI.shape[0]):
  squareFootage.append(int(squareFootageI[i].item()))
squareFootage = np.array(squareFootage)


numberOfOccupantsI = df.loc[:, ["Number of Occupants"]].values
numberOfOccupants = []
for i in range(numberOfOccupantsI.shape[0]):
  numberOfOccupants.append(int(numberOfOccupantsI[i].item()))
numberOfOccupants = np.array(numberOfOccupants)


appliancesUsedI = df.loc[:, ["Appliances Used"]].values
appliancesUsed = []
for i in range(appliancesUsedI.shape[0]):
  appliancesUsed.append(float(appliancesUsedI[i].item()))
appliancesUsed = np.array(appliancesUsed)


averageTemperatureI = df.loc[:, ["Average Temperature"]].values
averageTemperature = []
for i in range(averageTemperatureI.shape[0]):
  averageTemperature.append(float(averageTemperatureI[i].item()))
averageTemperature = np.array(averageTemperature)


dayOfWeekI = df.loc[:, ["Day of Week"]].values
dayOfWeek = []
for i in range(dayOfWeekI.shape[0]):
  if (dayOfWeekI[i] == "Weekend"):
    dayOfWeek.append(4)
  else:
    dayOfWeek.append(5)
dayOfWeek = np.array(dayOfWeek)


energyConsumptionI = df.loc[:, ["Energy Consumption"]].values
energyConsumption = []
for i in range(energyConsumptionI.shape[0]):
  energyConsumption.append(float(energyConsumptionI[i].item()))
energyConsumption = np.array(energyConsumption)


Xtest = np.column_stack((energyConsumption, squareFootage))
ytest = buildingTypeFiltered
print(Xtest.shape)
print(ytest.shape)


print(Xtest[:15])

(100, 4)
(100,)
[[2.45630e+04 4.00000e+00 1.50000e+01 2.86557e+03]
 [2.75830e+04 2.30000e+01 5.60000e+01 4.28380e+03]
 [4.53130e+04 4.40000e+01 4.00000e+00 5.06783e+03]
 [4.16250e+04 1.70000e+01 8.40000e+01 4.62430e+03]
 [3.67200e+04 4.70000e+01 5.80000e+01 4.82059e+03]
 [3.12070e+04 2.80000e+01 4.70000e+01 5.02623e+03]
 [3.92270e+04 4.40000e+01 1.80000e+01 4.40456e+03]
 [7.81400e+03 1.90000e+01 2.10000e+01 2.39437e+03]
 [2.04820e+04 1.60000e+01 2.40000e+01 3.96909e+03]
 [2.10300e+04 3.50000e+01 9.00000e+01 5.13669e+03]
 [4.14010e+04 1.50000e+01 8.70000e+01 5.16233e+03]
 [6.27900e+03 4.10000e+01 2.30000e+01 3.81009e+03]
 [3.19630e+04 2.00000e+01 2.00000e+00 4.40048e+03]
 [2.91870e+04 3.90000e+01 8.20000e+01 4.99164e+03]
 [1.39900e+04 2.70000e+01 8.00000e+01 4.47498e+03]]


In [10]:

class attentionRegression:
    def __init__(self, w=1.0):
        """
        Initialize the attention regression model.

        Parameters:
        w (float): Positive parameter controlling attention weight distribution
        """
        self.w = w
        self.X = None
        self.y = None

    def fit(self, X, y):
        """
        'Train' the model by storing the training data.

        Parameters:
        X (numpy.ndarray): Training data matrix of shape (n, d)
        y (numpy.ndarray): Training labels of shape (n,) or (n, 1)

        Returns:
        self: The fitted estimator
        """
        # Simply store the training data for later use
        self.X = X
        self.y = y.flatten() if len(y.shape) > 1 else y

        # Return self to allow method chaining
        return self

    def predict(self, X):
        """
        Predict numerical labels for samples in X.

        Parameters:
        X (numpy.ndarray): Test samples of shape (m, d)

        Returns:
        numpy.ndarray: Predicted values of shape (m,)
        """
        if self.X is None or self.y is None:
            raise ValueError("Model has not been fitted yet. Call 'fit' first.")

        # Initialize array for predictions
        predictions = np.zeros(X.shape[0])

        # For each test point
        for i, x_hat in enumerate(X):
            # Calculate Euclidean distances
            squared_diff = (self.X - x_hat)**2
            sum_squared_diff = np.sum(squared_diff, axis=1)
            distances = np.sqrt(sum_squared_diff)

            # Calculate attention scores
            attention_scores = np.exp(-distances/self.w)

            # Normalize to probability distribution
            epsilon = 1e-12
            probabilities = attention_scores / (np.sum(attention_scores) + epsilon)

            # Calculate weighted average
            predictions[i] = np.sum(probabilities * self.y)

        return predictions



# Function to implement the model selection
def select_best_model(Xtrain, ytrain, Xvalid, yvalid, w1, w2):
   """
   Select the better model between two attentionRegression models with different w values.

   Parameters:
   Xtrain (numpy.ndarray): Training data matrix of shape (n, d)
   ytrain (numpy.ndarray): Training labels of shape (n,) or (n, 1)
   Xvalid (numpy.ndarray): Validation data matrix of shape (m, d)
   yvalid (numpy.ndarray): Validation labels of shape (m,) or (m, 1)
   w1 (float): Hyperparameter value for first model
   w2 (float): Hyperparameter value for second model

   Returns:
   tuple: (better_model, better_w, better_error)
   """
   # Initialize models
   M1 = attentionRegression(w=w1)
   M1.fit(Xtrain, ytrain)

   M2 = attentionRegression(w=w2)
   M2.fit(Xtrain, ytrain)

   # Get predictions
   y1_pred = M1.predict(Xvalid)
   y2_pred = M2.predict(Xvalid)

   # Ensure yvalid is the right shape
   yvalid_flat = yvalid.flatten() if len(yvalid.shape) > 1 else yvalid

   # Compute Mean Squared Error
   error_M1 = np.mean((yvalid_flat - y1_pred) ** 2)
   error_M2 = np.mean((yvalid_flat - y2_pred) ** 2)

   # Select better model
   if error_M1 < error_M2:
       better_model = M1
       better_w = w1
       better_error = error_M1
   else:
       better_model = M2
       better_w = w2
       better_error = error_M2

   return better_model, better_w, better_error



w1, w2 = 0.1, 1.0
best_model, best_w, best_error = select_best_model(Xtrain, ytrain, Xtest, ytest, w1, w2)
print(f"Best model has w={best_w} with validation MSE: {best_error}")




Best model has w=1.0 with validation MSE: 1.6199985953485032


In [11]:
class LogisticRegressionGDwithRegularization(object):
    """Logistic Regression Classifier using gradient descent.

    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight
      initialization.


    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    loss_ : list
      Logistic loss function value in each epoch.

    """
    def __init__(self, eta=0.05, n_iter=100, alpha=0.1, random_state=2501):
        self.eta = eta
        self.n_iter = n_iter
        self.alpha = alpha  # Added parameter for L2 regularization
        self.random_state = random_state

    def fit(self, X, y, w=None):
        """ Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_examples, n_features]
          Training vectors, where n_examples is the number of examples and
          n_features is the number of features.
        y : array-like, shape = [n_examples]
          Target values.

        Returns
        -------
        self : object

        """
        if w is None:
            rgen = np.random.RandomState(self.random_state)
            self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        else:
            self.w_ = w
        # rgen = np.random.RandomState(self.random_state)
        # self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        self.loss_ = []

        for i in range(self.n_iter):
            net_input = self.net_input(X)
            output = self.activation(net_input)
            errors = (y - output)
            self.w_[1:] += self.eta * (X.T.dot(errors) - self.alpha * self.w_[1:]) # I added L2 penalty for weights meaning that I give a little looseness for my weights to prevent overfitting
            self.w_[0] += self.eta * errors.sum()

            # Clip the values of 'output' to avoid divide-by-zero errors
            output = np.clip(output, 1e-10, 1 - 1e-10)

            # compute the logistic `loss`
            loss = -y.dot(np.log(output)) - ((1 - y).dot(np.log(1 - output))) + (self.alpha / 2) * np.sum(self.w_[1:] ** 2) # Thanks to adding L2 Regularization (using formula for circle as it was shown on OneNote Whiteboard,
            # Lecture 6, Slide 3), I become less susceptible to overfitting giving my model a little "uncertainty"
            self.loss_.append(loss)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def activation(self, z):
        """Compute logistic sigmoid activation"""
        return 1. / (1. + np.exp(-np.clip(z, -250, 250)))

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, 0)
        # equivalent to:
        # return np.where(self.activation(self.net_input(X)) >= 0.5, 1, 0)

In [12]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_quadratic = PolynomialFeatures(degree=2)
polynomial_cubic = PolynomialFeatures(degree=3)
X_quadratic = polynomial_quadratic.fit_transform(Xtrain)
X_cubic = polynomial_cubic.fit_transform(Xtrain)


alphas = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

for i in alphas:
    model1 = LogisticRegressionGDwithRegularization(eta=0.0001, n_iter=1000, alpha=i)
    model2 = LogisticRegressionGDwithRegularization(eta=0.0001, n_iter=1000, alpha=i)
    model3 = LogisticRegressionGDwithRegularization(eta=0.0001, n_iter=1000, alpha=i)

    model1.fit(Xtrain, ytrain)
    model2.fit(X_quadratic, ytrain)
    model3.fit(X_cubic, ytrain)

    print("Alpha = ", i)
    print("Linear model loss: ", model1.loss_[-1])
    print("Linear model norm: ", np.linalg.norm(model1.w_))
    print("Quadratic model loss: ", model2.loss_[-1])
    print("Quadratic model norm: ", np.linalg.norm(model2.w_))
    print("Cubic model loss: ", model3.loss_[-1])
    print("Cubic model norm: ", np.linalg.norm(model3.w_))

Alpha =  0.0
Linear model loss:  391.4394645007019
Linear model norm:  28280.747320953575
Quadratic model loss:  483.5428678891021
Quadratic model norm:  828590719.9207109
Cubic model loss:  529.5945695833022
Cubic model norm:  28395064777635.996
Alpha =  0.1
Linear model loss:  39586520.03832007
Linear model norm:  28137.565186288088
Quadratic model loss:  3.3987932724082084e+16
Quadratic model norm:  824474774.9213629
Cubic model loss:  3.992121548254261e+25
Cubic model norm:  28256402985002.39
Alpha =  0.2
Linear model loss:  78393249.04522033
Linear model norm:  27998.724590465434
Quadratic model loss:  6.728448570789568e+16
Quadratic model norm:  820271209.4660838
Cubic model loss:  7.911000352865319e+25
Cubic model norm:  28126500587284.797
Alpha =  0.3
Linear model loss:  116399854.93294628
Linear model norm:  27856.712403399357
Quadratic model loss:  9.995834875341254e+16
Quadratic model norm:  816326522.7158885
Cubic model loss:  1.1720017133933907e+26
Cubic model norm:  27952